# Generated by Django 5.2.1 on 2026-03-12 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aad_tenant_id', models.CharField(max_length=120)),
                ('client_id', models.CharField(max_length=120)),
                ('client_secret', models.CharField(max_length=255)),
                ('scope', models.CharField(default='https://analysis.windows.net/powerbi/api/.default', max_length=255)),
                ('api_base_url', models.URLField(default='https://api.powerbi.com/v1.0/myorg')),
                ('default_workspace_id', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_connection', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name'],
            },
        ),
        migrations.CreateModel(
            name='PowerBIGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('external_gateway_id', models.CharField(max_length=180)),
                ('gateway_type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('error', 'Erro')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways', to='powerbi.powerbiconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_gateways', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PowerBIGatewayDataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('external_datasource_id', models.CharField(max_length=180)),
                ('datasource_type', models.CharField(blank=True, max_length=80)),
                ('connection_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='powerbi.powerbigateway')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='powerbigateway',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_gateway_id'), name='unique_gateway_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='powerbigatewaydatasource',
            constraint=models.UniqueConstraint(fields=('gateway', 'external_datasource_id'), name='unique_datasource_per_gateway'),
        ),
    ]
