# Generated by Django 5.2.1 on 2026-03-11 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('denied', 'Negado'), ('error', 'Erro')], default='success', max_length=20)),
                ('origin', models.CharField(choices=[('portal', 'Portal'), ('api', 'API'), ('mobile', 'Mobile')], default='portal', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='dashboards.dashboard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
