# Generated by Django 5.2.1 on 2026-03-18 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('tenants', '0003_tenant_support_hours_consumed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('auth', 'Auth'), ('authorization', 'Authorization'), ('admin', 'Admin'), ('integration', 'Integration'), ('system', 'System')], default='system', max_length=30)),
                ('action', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('resource_type', models.CharField(blank=True, max_length=120)),
                ('resource_id', models.CharField(blank=True, max_length=120)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'level', 'created_at'], name='audit_syste_categor_60fdc7_idx'), models.Index(fields=['tenant', 'created_at'], name='audit_syste_tenant__f947d2_idx'), models.Index(fields=['user', 'created_at'], name='audit_syste_user_id_84f1ec_idx')],
            },
        ),
    ]
