# Generated by Django 5.2.1 on 2026-03-11 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(max_length=180)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#0f6fe8', max_length=12)),
                ('secondary_color', models.CharField(default='#14b8a6', max_length=12)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('custom_domain_enabled', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name'],
            },
        ),
    ]
