# Generated by Django 5.2.1 on 2026-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlsrule',
            name='operator',
            field=models.CharField(choices=[('in', 'IN'), ('not_in', 'NOT IN')], default='in', max_length=20),
        ),
        migrations.AddField(
            model_name='rlsrule',
            name='table_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
