# Generated by Django 5.2.1 on 2026-03-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='support_hours_consumed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='support_hours_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
