# Generated by Django 5.2.1 on 2026-03-11 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('draft', 'Rascunho'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('embed_url', models.URLField(blank=True)),
                ('report_id', models.CharField(blank=True, max_length=160)),
                ('dataset_id', models.CharField(blank=True, max_length=160)),
                ('external_workspace_id', models.CharField(blank=True, max_length=160)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_schedule', models.CharField(blank=True, max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='tenants.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('values', models.JSONField(blank=True, default=list)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_dashboard_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='dashboardcolumn',
            constraint=models.UniqueConstraint(fields=('dashboard', 'name'), name='unique_column_name_per_dashboard'),
        ),
    ]
