# Generated by Django 5.2.1 on 2026-03-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='embed_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
